stages:
  - test
  - build
  - integration

sudo: required

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - KUBECONFIG=$HOME/.kube/config
before_install:
  - sudo apt-get -qq -y install conntrack

jobs:
  include:
    - stage: test
      language: go
      go: "1.16"
      script:
        - make install-kubebuilder KUBEBUILDER_INSTALL_DIR=/tmp/kubebuilder
        - export TEST_ASSET_KUBECTL=/tmp/kubebuilder/bin/kubectl
        - export TEST_ASSET_KUBE_APISERVER=/tmp/kubebuilder/bin/kube-apiserver
        - export TEST_ASSET_ETCD=/tmp/kubebuilder/bin/etcd
        - make test

    - stage: build
      if: type == pull_request
      branches:
        except:
          - master
      language: bash
      sudo: required
      script:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t shipasoftware/ketch:$TRAVIS_COMMIT .
        - docker push shipasoftware/ketch:$TRAVIS_COMMIT

    - stage: integration
      sudo: required
      dist: xenial

      before_script:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.16.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
        - mkdir -p $HOME/.kube $HOME/.minikube
        - touch "$KUBECONFIG"
        - sudo minikube start --profile=minikube --vm-driver=none --kubernetes-version=v1.20.1
        - minikube update-context --profile=minikube
        - "sudo chown -R travis: /home/travis/.minikube/"
        - eval "$(minikube docker-env --profile=minikube)" && export DOCKER_CLI='docker'
        # TODO - rm and rely on push from docker repo, make type == PR
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - docker build -t shipasoftware/ketch:$TRAVIS_COMMIT .
        - docker push shipasoftware/ketch:$TRAVIS_COMMIT
      script:
        - kubectl cluster-info
        # TODO - create actual test
        - make install-kubebuilder KUBEBUILDER_INSTALL_DIR=/tmp/kubebuilder
        - make controller-gen
        # - make install
        # - make deploy IMG=shipasoftware/ketch:$TRAVIS_COMMIT
        # - cd cmd/ketch && go build -o ketch .
        # - ./ketch --version
